export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const LOGOUT = "LOGOUT";
export const CREATE_CLASS = "CREATE_CLASS";
export const GET_ALL_CLASSES = 'GET_ALL_CLASSES';
export const GET_ALL_JOINED_CLASSES = "GET_ALL_JOINED_CLASSES";

